name: Lint, Test, Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js
        uses: action/setup-node@v1
        with:
          node-version: [17.x]
#      - name: start_desktop
#        uses: docker/desktop-action/start@v0.1.0
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts-check
      - name: linting  SCSS CSS files
        run: npm run lint:scss-check
      - name: unit testing
        run: npm run test:unit
