name: Lint, Test, Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '17.x'
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts-check
      - name:  linting  SCSS CSS files
        run: npm run lint:scss-check
      - name: unit testing
        run: npm run test:unit
      - name: build Storybook static files
        run: npm run storybook:build
      - name: run Storybook
        run: npm run storybook
      - name: screenshot testing ui
        run: npm run test:ui
      - name: screenshot testing ci
        run: npm run test:ui:ci
